name: Azure Dev

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: openchat-playground

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      GH_MODELS_TOKEN: ${{ secrets.GH_MODELS_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Setup Ollama
      uses: ai-action/setup-ollama@v1

    - uses: actions/cache@v4
      with:
        path: ~/.ollama
        key: ${{ runner.os }}-ollama

    - name: Install local certs
      shell: bash
      run: |
        dotnet dev-certs https --trust

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build -c Release --no-restore --no-incremental

    - name: Run unit tests
      shell: bash
      run: |
        dotnet test . -c Release --no-build --logger "trx" --collect:"XPlat Code Coverage" --filter "Category=UnitTest"

    - name: Install playwright
      shell: pwsh
      run: |
        $playwright = Get-ChildItem -File Microsoft.Playwright.dll -Path . -Recurse
        $installer = "$($playwright[0].Directory.FullName)/playwright.ps1"
        & "$installer" install

    - name: Run Ollama server
      shell: bash
      run: |
        ollama run hf.co/Qwen/Qwen3-0.6B-GGUF &

    - name: Run app in background
      shell: bash
      run: |
        dotnet user-secrets --project ./src/OpenChat.PlaygroundApp \
            set GitHubModels:Token "temporary-dummy-token"

        dotnet run --project ./src/OpenChat.PlaygroundApp -- \
            --connector-type HuggingFace &

        sleep 30

    - name: Run integration tests
      shell: bash
      run: |
        dotnet test ./test/OpenChat.PlaygroundApp.Tests -c Release \
            --no-build --logger "trx" --collect:"XPlat Code Coverage" \
            --filter "Category=IntegrationTest & Category!=IgnoreGitHubActions"

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/Dockerfile
        tags: '${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest'
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Install azd
      uses: Azure/setup-azd@v2

    - name: Log in with Azure
      shell: pwsh
      run: |
        azd auth login `
          --client-id "$env:AZURE_CLIENT_ID" `
          --federated-credential-provider "github" `
          --tenant-id "$env:AZURE_TENANT_ID"

    - name: Provision Infrastructure
      shell: bash
      env:
        GitHubModels__Token: ${{ env.GH_MODELS_TOKEN }}
        Anthropic__ApiKey: ${{ env.ANTHROPIC_API_KEY }}
        OpenAI__ApiKey: ${{ env.OPENAI_API_KEY }}
      run: |
        azd provision --no-prompt

    - name: Deploy Application
      shell: bash
      run: |
        azd deploy --no-prompt
